version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  webssh:
    image: reg.dc.celp.red/lacnog/webssh 
    labels:
      - traefik.http.routers.blog.rule=Host(`vxlan.nog.lat`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=8022
#    networks:
#      - internal
#      - web