version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  webssh:
    image: reg.dc.celp.red/lacnog/webssh 
    hostname: webssh
    labels:
      - traefik.http.routers.webssh.rule=Host(`ssh.nog.lat`)
      - traefik.http.routers.webssh.tls=true
      - traefik.http.routers.webssh.tls.certresolver=lets-encrypt
      - traefik.http.services.webssh.loadbalancer.server.port=80
    networks:
      - web
      - internal
  
  docs:
    image: reg.dc.celp.red/lacnog/doc-lab-vxlan-evpn
    hostname: docs
    labels:
      - traefik.http.routers.docs.rule=Host(`vxlan.nog.lat`)
      - traefik.http.routers.docs.tls=true
      - traefik.http.routers.docs.tls.certresolver=lets-encrypt
      - traefik.http.services.docs.loadbalancer.server.port=80
    networks:
      - web
      - internal
  
  consoler:
    image: reg.dc.celp.red/lacnog/consoler
    hostname: consoler
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/BuenosAires
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_NAME=lablacnog
      - USER_PASSWORD=RadiaPerlman
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped