[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$7fxxyHZu$9zBTmHDqGTeQyzUcEKAEa0"
  ]

[http.routers.api]
  rule = "Host(`monitor.lacnog2022.labs.nog.lat`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"