[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$HBiFTJR4$Yxl5w/Ibu6UqksBUNU.yd1" #admin:RADIAProvoloneLACNOG (yes, I know...)
  ]

[http.routers.api]
  rule = "Host(`monitor.vxlan.nog.lat`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"